// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteMemeFile(arg1, arg2, arg3) {
  return window['go']['memeFile']['MemeFile']['DeleteMemeFile'](arg1, arg2, arg3);
}

export function DeleteTgStickerSet(arg1, arg2) {
  return window['go']['memeFile']['MemeFile']['DeleteTgStickerSet'](arg1, arg2);
}

export function DownloadTgStickerSet(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['memeFile']['MemeFile']['DownloadTgStickerSet'](arg1, arg2, arg3, arg4, arg5);
}

export function GenerateAllMemePath(arg1) {
  return window['go']['memeFile']['MemeFile']['GenerateAllMemePath'](arg1);
}

export function GetDirs(arg1) {
  return window['go']['memeFile']['MemeFile']['GetDirs'](arg1);
}

export function GetImages(arg1) {
  return window['go']['memeFile']['MemeFile']['GetImages'](arg1);
}

export function OpenFileDlg() {
  return window['go']['memeFile']['MemeFile']['OpenFileDlg']();
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['memeFile']['MemeFile']['RenameFile'](arg1, arg2, arg3);
}

export function RenameFilesInOrder(arg1, arg2, arg3) {
  return window['go']['memeFile']['MemeFile']['RenameFilesInOrder'](arg1, arg2, arg3);
}

export function RenameFoldersInOrder(arg1, arg2) {
  return window['go']['memeFile']['MemeFile']['RenameFoldersInOrder'](arg1, arg2);
}

export function SelectRootDir() {
  return window['go']['memeFile']['MemeFile']['SelectRootDir']();
}

export function SetContext(arg1) {
  return window['go']['memeFile']['MemeFile']['SetContext'](arg1);
}

export function WriteFileToClipboard(arg1) {
  return window['go']['memeFile']['MemeFile']['WriteFileToClipboard'](arg1);
}
