// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {memeFile} from '../models';
import {context} from '../models';

export function GenerateAllMemePath(arg1:string):Promise<Array<memeFile.MemeInfo>>;

export function GetDirs(arg1:string):Promise<Array<string>>;

export function GetImages(arg1:string):Promise<Array<string>>;

export function Hello():Promise<string>;

export function OpenFileDlg():Promise<Array<string>>;

export function SelectRootDir():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
