// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateAllMemePath(arg1) {
  return window['go']['memeFile']['MemeFile']['GenerateAllMemePath'](arg1);
}

export function GetDirs(arg1) {
  return window['go']['memeFile']['MemeFile']['GetDirs'](arg1);
}

export function GetImages(arg1) {
  return window['go']['memeFile']['MemeFile']['GetImages'](arg1);
}

export function Hello() {
  return window['go']['memeFile']['MemeFile']['Hello']();
}

export function OpenFileDlg() {
  return window['go']['memeFile']['MemeFile']['OpenFileDlg']();
}

export function SelectRootDir() {
  return window['go']['memeFile']['MemeFile']['SelectRootDir']();
}

export function SetContext(arg1) {
  return window['go']['memeFile']['MemeFile']['SetContext'](arg1);
}
